### ISSUE TITLE
Typescript dependency error when running from docker

### ISSUE THREAD

**Issue by bewell** [SonarSource/sonar-scanner-cli-docker#102]
Hi guys,

I'm trying to run Sonarscanner from gitlab pipeline.  The action looks like this:
```
sonarqube-check:
  stage: security-testing
  image: sonarsource/sonar-scanner-cli:latest
  except:
    - /^release-.*$/
  needs: []
  allow_failure: true
  variables:
    # Defines the location of the analysis task cache
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    # Tells git to fetch all the branches of the project, required by the analysis task
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    # installing NodeJS on the runner so that analysis can occur
    - apk add --update nodejs npm
    - apk add --update npm
    - npm install -g typescript
    # running the actual analysis    
    - sonar-scanner -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.qualitygate.wait=true
```

The problem I have is with Typescript. Sonar was complaining that typescript was not found so I've added the steps to the preparation. Although that didn't seem to solve the issue.

The error I get is still this:
```
INFO: Sensor TypeScript analysis [javascript] (done) | time=76msERROR: Install TypeScript in the project directory or use NODE_PATH env. variable to set TypeScript location, if it's located outside of project directory.
ERROR: Missing TypeScript dependency
```

What am I doing wrong?
Thanks!
