### ISSUE TITLE
After not-installing NPM anymore scanning of TypeScript projects fail

### ISSUE THREAD

**Issue by mallwang** [SonarSource/sonar-scanner-cli-docker#145]
Hi,

we are using the sonar-scanner-cli Docker image during our CI pipeline for scanning TypeScript projects. By default, TypeScript is not installed on the image so that we initially received an error "Cannot find module typescript" (see https://community.sonarsource.com/t/error-cannot-find-module-typescript/4396). We could solve it via installing the current TypeScript version we are really using (`npm i typescript@$(node -p "require('./package.json').devDependencies.typescript")`).

This worked well until you dont install NPM anymore (#142), since then this command cannot be executed and throws an error (`npm: command not found`). Our workaround now would be to install npm ourselves (`apk add 'npm>7'`) but this means that we also need to maintain it ourselves.

I am just asking: is there a chance that you revert these changes again or are you concerned about potential security issues when npm is installed or what was the reason for the removal? For us its not a big deal to install npm but I could imagine that sometime in the future when the image will not run as root anymore our solution would not be possible anymore.

Anyway, many thanks for providing this great software, we really appreciate it and cannot imaging a world without it 😍

**Comment by wysstobi** [comment]
Hi @mallwang 
Do you still get the scan working? Even if I manually install `npm` and `typescript` the scan fails with:
`ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Unable to load component class org.sonar.plugins.javascript.JavaScriptSensor`
Followed by a long stack trace.

**Comment by mallwang** [comment]
Hi @wysstobi,

yes the scan still works using our workaround solution (Typescript 4), see the following snippet (GitLab CI):

```yaml
# TEMPLATES
.analyze-sonarqube:
  image:
    name: sonarsource/sonar-scanner-cli:4.8.1
    entrypoint: ['']
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar' # Defines the location of the analysis task cache
    GIT_DEPTH: '' # Disable git shallow clone for SonarQube analysis to fetch the complete history
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - echo "scanning project key '${ANALYZE_SONARQUBE_PROJECT_KEY}' to SonarQube host '${ANALYZE_SONARQUBE_HOST_URL}'"
    - sonar-scanner
      -Dsonar.projectKey=${ANALYZE_SONARQUBE_PROJECT_KEY}
      -Dsonar.host.url=${ANALYZE_SONARQUBE_HOST_URL}
      -Dsonar.login=${ANALYZE_SONARQUBE_TOKEN}

.analyze-sonarqube-typescript:
  extends: [.analyze-sonarqube]
  before_script:
    - cd ${SCAN_DIRECTORY}
    # manually install npm (see https://github.com/SonarSource/sonar-scanner-cli-docker/pull/142)
    - apk add --no-cache 'npm>7'
    # install same typescript version like in package.json
    - npm i typescript@$(node -p "require('./package.json').devDependencies.typescript") --force

# JOBS
analyze-sonarqube-frontend:
  stage: code-scanning
  needs: [test-frontend]
  extends: [.analyze-sonarqube-typescript]
  variables:
    ANALYZE_SONARQUBE_PROJECT_KEY: ${ANALYZE_SONARQUBE_PROJECT_KEY_FRONTEND}
    SCAN_DIRECTORY: ${PACKAGES_DIR}/${FRONTEND_DIR}
```

For all new projects using TypeScript 5, we only use the default GitLab CI template and it works without any workarounds:
```yaml
analyze-sonarqube:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: ['']
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar' # Defines the location of the analysis task cache
    GIT_DEPTH: '0' # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - echo "scanning directory '${SCAN_DIRECTORY}' to SonarQube host '${ANALYZE_SONARQUBE_HOST_URL}'"
    - cd ${SCAN_DIRECTORY}
    - sonar-scanner
      -Dsonar.host.url=${ANALYZE_SONARQUBE_HOST_URL}
      -Dsonar.login=${ANALYZE_SONARQUBE_TOKEN}
      -Dsonar.qualitygate.wait=true
```

Results:  
![image](https://github.com/SonarSource/sonar-scanner-cli-docker/assets/7611485/8913a069-e616-40a2-ae15-e6a1a4c62cb1)

Since the scanning works without modifications and all TypeScript files are correctly scanned, the issue is not applicable anymore for us and once we upgrade the problematic/oudated project to a newer TypeScript version, I assume that it will also work without the workaround. We did therefore not spend any further time in investigation ;)

Hope that helps somehow ;/

Regards,
Markus
