### ISSUE TITLE
Shell not found with 4.8+

### ISSUE THREAD

**Issue by struct78** [SonarSource/sonar-scanner-cli-docker#173]
We are using sonarcloud-scanner-cli:latest with Gitlab cloud, and noticed since the last release a few days ago, our analysis steps are failing with the following:

```
Using docker image sha256:84fb05011f5cda03c464cc22ce519a4500aabf6bad2cfe2edc0e3556c26bd382 for sonarsource/sonar-scanner-cli:latest
shell not found
``` 

We are running:
- Gitlab 15.1.0
- Node 14

Our .gitlab-ci.yml file looks like this:

```
analysis:
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  stage: analysis
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  rules:
    - if: ($CI_COMMIT_BRANCH == "master" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master")
      when: always
      changes:
        - app/src/**/*
        - functions/src/**/*
  script:
    - sonar-scanner
 ```
 
 Unfortunately I can't get any more details!
