### ISSUE TITLE
Document how to pass properties

### ISSUE THREAD

**Issue by lenntt** [SonarSource/sonar-scanner-cli-docker#26]
Running the examples gives me: 
```
ERROR: You must define the following mandatory properties for 'Unknown': sonar.projectKey
```
(which makes sense)

However, I don't know how to pass this and other properties (like properties file, branch name etc)

**Comment by Keuthonymous** [comment]
> Running the examples gives me:
> 
> ```
> ERROR: You must define the following mandatory properties for 'Unknown': sonar.projectKey
> ```
> 
> (which makes sense)
> 
> However, I don't know how to pass this and other properties (like properties file, branch name etc)

If you take a look at the entrypoint.sh file, you can see the environment variables that are currently available. I encountered the same error that you were having and simply added a new line using the same method that was already there to add a projectKey variable. Any other variables you might need can also be added there. Then just build and run like normal. There is probably a better way of doing this, but I don't know shell script, so someone else should come up with that solution.

**Comment by lenntt** [comment]
It seems https://github.com/SonarSource/sonar-scanner-cli-docker/pull/14 would fix my issue.
The docker image, as is, is quite useless to me now.

**Comment by kav** [comment]
You can use a sonar-project.properties file in the same directory as your source code. Does that not work for your use case?

See https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/

**Comment by lenntt** [comment]
not really, there's some dynamic properties I inject via CI, like branch names and pull request ids. I'm hoping #36 gets merged, which solves this issue

**Comment by kav** [comment]
I just overrode the command and passed `-D` props as that pr does but agreed.

**Comment by michal-duda-sonarsource** [comment]
In version 4.4 you can pass all analysis parameters like you would pass them to `sonar-scanner`:
```
docker run -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli -Dsonar.projectKey=${SONAR_PROJECT_KEY}
```
You can find the docs here: https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/

**Comment by buddhamangler-cbre** [comment]
> In version 4.4 you can pass all analysis parameters like you would pass them to `sonar-scanner`:
> 
> ```
> docker run -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli -Dsonar.projectKey=${SONAR_PROJECT_KEY}
> ```
> 
> You can find the docs here: https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/

this is not clear, at least to me, from the docs you linked.  I think the documentation could be a little more explicit there as I struggled for a few hours hunting down the correct Environment variables to set without success until i found this post, then i was good to go.

**Comment by ievgennaida** [comment]
Could you please also provide an example with docker-compose?

**Comment by kav** [comment]
See https://docs.docker.com/compose/compose-file/#command

**Comment by matheus-silva-gaivota** [comment]
How could I send the `sonar.projectKey` in my `docker-compose.yml`?

```
version: '3.8'

services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    hostname: sonarqube
    networks:
      - sonarnet
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  sonarscanner:
    container_name: sonarscanner
    image: sonarsource/sonar-scanner-cli
    restart: on-failure
    networks:
      - sonarnet
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_LOGIN=00892ff3700736977df49c0cfd1c9777234e9e5f
      - SONAR_PROJECT_KEY=test
    volumes:
      - ./sonarscanner:/usr/src/
networks:
  sonarnet:
    driver: bridge
```

Could someone help me to find what's going wrong?
